version: '3'
services:
  # mongodb
  lego-mongo:
    image : mongo:5
    container_name : lego-mongo
    volumes:
      - '.docker-volumes/mongo/data:/data/db'
      - './mongo-entrypoint/:/docker-entrypoint-initdb.d/'
    ports:
      - 27018:27017
    env_file:
      - .env
  # redis
  lego-redis:
    image: redis:6
    container_name: lego-redis
    ports:
      - 6380:6379
    command: >
      --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
  # egg
  lego-backend:
    depends_on:
      - lego-mongo
      - lego-redis
    build: 
      context: .
      dockerfile: Dockerfile
    image: lego-backend
    container_name: lego-backend
    ports:
      - 7002:7001
    env_file:
      - .env