version: '3'
services:
  # mongodb
  lego-mongo:
    image : mongo
    container_name : lego-mongo
    volumes:
      - '.docker-volumes/mongo/data:/data/db'
    ports:
      - 27017:27017
  # redis
  lego-redis:
    image: redis
    container_name: lego-redis
    ports:
      - 6379:6379
  # egg
  lego-backend:
    depends_on:
      - lego-mongo
      # - lego-redis
    build: 
      context: .
      dockerfile: Dockerfile
    image: lego-backend
    container_name: lego-backend
    ports:
      - 7001:7001