name: tag test
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # github context
      - name: 'test github context info'
        run: |
          echo ${{github.ref}}
          echo ${{github.ref_name}}
          echo ${{github.sha}}
      - name: Find and replace
        uses: jacobtomlinson/gha-find-replace@v2
          with:
            find: "{{tag}}"
            replace: ${{github.ref_name}}
            include: "docker-compose-online.yml"
      - run: cat docker-compose-online.yml